'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FreeLandManagementWindow

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''EditFreeLandHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EditFreeLandNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EditFreeLandCompanyNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandCompanyNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandCompanyNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandCompanyNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EditFreeLandProvinceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandProvinceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewProvince As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''EditFreeLandProvinceComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandProvinceComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''EditFreeLandProvinceRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandProvinceRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EditFreeLandVillageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandVillageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addnewVillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addnewVillage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''EditFreeLandVillageComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandVillageComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''EditFreeLandVillageRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandVillageRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EditFreeLandMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandMemoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandMemoRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EditFreeLandOfficalNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandOfficalNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandOfficalNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandOfficalNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EditFreeLandRentPriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandRentPriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandRentingPriceTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandRentingPriceTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''EditFreeLandrentPriceRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandrentPriceRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EditFreeLandCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewCity As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''EditFreeLandCityComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandCityComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''EditFreeLandCityRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandCityRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EditFreeLandPlaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandPlaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandPlaceRadTExtBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandPlaceRadTExtBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EditFreeLandAttachment1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandAttachment1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditFreeLandAttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditFreeLandAttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''FreeLandUploadedLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandUploadedLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''AddBasicData_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddBasicData_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''ImageView_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageView_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''SqlDataSource_FreeLand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_FreeLand As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ProvincesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ProvincesList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_CityList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_CityList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_VillageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_VillageList As Global.System.Web.UI.WebControls.SqlDataSource
End Class
