'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FreeLandManagement

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''HeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreelandNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreeLandNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FreeLandNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FreelandCompanyNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandCompanyNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreeLandCompanyNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandCompanyNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FreelandProvinceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandProvinceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewProvince As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FreelandProvinceComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandProvinceComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FreelandVillageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandVillageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addnewVillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addnewVillage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FreelandVillageComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandVillageComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FreelandMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreelandMemoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandMemoRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FreeLandOfficalNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandOfficalNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreeLandOfficalNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandOfficalNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FreelandRentPriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandRentPriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreeLandRentingPriceTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandRentingPriceTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''FreeLandrentPriceRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandrentPriceRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FreelandCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewCity As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FreelandCityComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandCityComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FreelandPlaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandPlaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreelandPlaceRadTExtBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreelandPlaceRadTExtBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FreeLandAttachment1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandAttachment1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FreeLandAttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLandAttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''freeLandradGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents freeLandradGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''AddBasicData_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddBasicData_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''FreeLand_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FreeLand_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''SqlDataSource_ProvincesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ProvincesList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_CityList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_CityList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_VillageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_VillageList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_FreeLand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_FreeLand As Global.System.Web.UI.WebControls.SqlDataSource
End Class
