'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VillaManagement

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''HeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''VillaCompanyNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaCompanyNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaCompanyNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaCompanyNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaProvinceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaProvinceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewProvince As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''VillaProvinceComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaProvinceComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''VillaProvinceComboBoxRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaProvinceComboBoxRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''VillaVillageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaVillageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addnewVillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addnewVillage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''VillaVillageComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaVillageComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''VillaVillageComboBoxRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaVillageComboBoxRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''VillaRoomNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaRoomNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaRoomNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaRoomNoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaBathRoomTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaBathRoomTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaBathRoomTypeComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaBathRoomTypeComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''VillaMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaMemoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaMemoRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaOfficalNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaOfficalNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaOfficalNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaOfficalNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaRentPriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaRentPriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaRentPriceRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaRentPriceRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''VillarentPriceRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillarentPriceRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''VillaCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewCity As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''VillaCityComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaCityComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''VillaCityComboBoxRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaCityComboBoxRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''VillaPlaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaPlaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaPlaceRadTExtBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaPlaceRadTExtBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaFloorNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaFloorNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaFloorNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaFloorNoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaBathroomNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaBathroomNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaBathroomNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaBathroomNoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''VillaAttachment1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaAttachment1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VillaAttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaAttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''VillaradGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VillaradGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''AddBasicData_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddBasicData_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''Villa_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Villa_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''SqlDataSource_ProvincesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ProvincesList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_CityList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_CityList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_VillageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_VillageList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Villa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Villa As Global.System.Web.UI.WebControls.SqlDataSource
End Class
