'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ContactManagement

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''Master_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Master_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''HeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ContactGSM1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactGSM1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactGSM1ContryCodeCombobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactGSM1ContryCodeCombobox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ContactGSM1TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactGSM1TextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactGSM1Required control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactGSM1Required As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ContactIdentityNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactIdentityNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactIdentityNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactIdentityNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactCommercialRegisterNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactCommercialRegisterNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactCommercialRegisterNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactCommercialRegisterNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactEmailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactEmailTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactLatitudeCoordinatesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactLatitudeCoordinatesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactLatitudeCoordinatesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactLatitudeCoordinatesTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ContactOfficeFaxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactOfficeFaxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactOfficeFaxTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactOfficeFaxTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactPOBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactPOBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactPOBoxTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactPOBoxTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactURLMapLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactURLMapLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactURLMapTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactURLMapTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactNickNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNickNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactNickNameComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNickNameComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ContactGSM2Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactGSM2Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactGSM2ContryCodeCombobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactGSM2ContryCodeCombobox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ContactGSM2TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactGSM2TextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactOfficePhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactOfficePhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactOfficePhoneTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactOfficePhoneTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactWebsiteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactWebsiteLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactWebsiteTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactWebsiteTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactPostalCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactPostalCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactPostalCodeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactPostalCodeTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactLongitudeCoordinatesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactLongitudeCoordinatesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactLongitudeCoordinatesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactLongitudeCoordinatesTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ContactMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactMemoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactMemoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ContactIdentityAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactIdentityAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactIdentityUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactIdentityUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''ContactCommercialRegisterLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactCommercialRegisterLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactCommercialRegisterUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactCommercialRegisterUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ContactRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SqlDataSource_ContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ContactList As Global.System.Web.UI.WebControls.SqlDataSource
End Class
