'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BankAccountOpeningBalanceManagement

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''UpdateBankAccountOpeningBalanceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateBankAccountOpeningBalanceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OldOpeningBalanceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OldOpeningBalanceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OldOpeningBalanceTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OldOpeningBalanceTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''OldBankAccountOpeningBalanceMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OldBankAccountOpeningBalanceMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OldBankAccountOpeningBalanceMemoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OldBankAccountOpeningBalanceMemoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''NewOpeningBalanceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewOpeningBalanceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewOpeningBalanceTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewOpeningBalanceTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''NewOpeningBalanceRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewOpeningBalanceRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NewBankAccountOpeningBalanceMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewBankAccountOpeningBalanceMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewBankAccountOpeningBalanceMemoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewBankAccountOpeningBalanceMemoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OpeningBalanceUserSignatureLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpeningBalanceUserSignatureLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OpeningBalanceUserSignatureTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpeningBalanceUserSignatureTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OpeningBalanceUserSignatureRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpeningBalanceUserSignatureRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OpeningBalanceCancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpeningBalanceCancelButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''OpeningBalanceSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpeningBalanceSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock
End Class
