'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BankAccountManagementWindow

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''createBankAccountHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createBankAccountHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankAccountNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankAccountNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankAccountNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BankAccountArabicNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountArabicNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankAccountArabicNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountArabicNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankAccountArabicNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountArabicNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BankAccountEnglishNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountEnglishNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankAccountEnglishNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountEnglishNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankAccountEnglishNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountEnglishNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BankAccountMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankAccountMemoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountMemoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock
End Class
