'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BankManagement

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankArabicNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankArabicNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankArabicNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankArabicNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankArabicNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankArabicNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BankSwiftCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankSwiftCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankSwiftCodeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankSwiftCodeTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankLatitudeCoordinatesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankLatitudeCoordinatesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankLatitudeCoordinatesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankLatitudeCoordinatesTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BankURLMapLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankURLMapLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankURLMapTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankURLMapTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankOnlineBankingURLLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankOnlineBankingURLLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankOnlineBankingURLTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankOnlineBankingURLTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankWebsiteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankWebsiteLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankWebsiteTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankWebsiteTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankEnglishNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankEnglishNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankEnglishNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankEnglishNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankEnglishNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankEnglishNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BankIBANCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankIBANCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankIBANCodeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankIBANCodeTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BankLongitudeCoordinatesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankLongitudeCoordinatesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankLongitudeCoordinatesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankLongitudeCoordinatesTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BankDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankDescriptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankDescriptionTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankDescriptionTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''BankRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''radCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCodeBlock As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SqlDataSource_BankList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BankList As Global.System.Web.UI.WebControls.SqlDataSource
End Class
