'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BankAccountTransaction

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''TranscationHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TranscationHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionBankLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionBankLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionBankComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionBankComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionBankRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionBankRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionDocumentTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionDocumentTypeComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentTypeComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionDocumentTypeRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentTypeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionAmountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAmountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionAmountTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAmountTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''TransactionAmountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAmountRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionDocumentDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionDocumentDateDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentDateDatePicker As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''TransactionDocumentDateRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentDateRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TreasurerSignatureLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreasurerSignatureLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TreasurerSignatureTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreasurerSignatureTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''TreasurerSignatureRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreasurerSignatureRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionAttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''TransactionBankAccountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionBankAccountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionBankAccountComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionBankAccountComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionBankAccountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionBankAccountRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionDocumentNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionDocumentNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''TransactionDocumentNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BankAccountTotalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountTotalLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BankAccountTotalTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountTotalTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''TransactionTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionTypeComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionTypeComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionTypeRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionTypeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionMemoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionMemoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''BankAccountTransactionRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankAccountTransactionRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SqlDataSource_BankList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BankList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_BankAccountList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BankAccountList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_BankAccountTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BankAccountTransaction As Global.System.Web.UI.WebControls.SqlDataSource
End Class
