'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TransferCashBetweenBankAccounts

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''subHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionSenderBankLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSenderBankLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionSenderBankComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSenderBankComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionSenderBankRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSenderBankRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionSenderBankAccountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSenderBankAccountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionSenderBankAccountComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSenderBankAccountComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionSenderBankAccountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSenderBankAccountRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SenderBankAccountTotalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderBankAccountTotalLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SenderBankAccountTotalTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderBankAccountTotalTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionRecieveBankLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionRecieveBankLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionRecieveBankComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionRecieveBankComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionRecieveBankRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionRecieveBankRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionRecieveBankAccountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionRecieveBankAccountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionRecieveBankAccountComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionRecieveBankAccountComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionRecieveBankAccountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionRecieveBankAccountRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RecieveBankAccountTotalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecieveBankAccountTotalLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecieveBankAccountTotalTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecieveBankAccountTotalTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''TransactionDocumentTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionDocumentTypeComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentTypeComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TransactionDocumentTypeRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentTypeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionAmountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAmountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionAmountTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAmountTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''TransactionAmountRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAmountRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TreasurerSignatureLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreasurerSignatureLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TreasurerSignatureTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreasurerSignatureTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''TreasurerSignatureRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreasurerSignatureRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionAttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionAttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''TransactionDocumentNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionDocumentNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''TransactionDocumentNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionDocumentDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionDocumentDateDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentDateDatePicker As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''TransactionDocumentDateRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDocumentDateRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransactionMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionMemoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionMemoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''TransactionBetweenBankAccountsRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionBetweenBankAccountsRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SqlDataSource_BankList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BankList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_BankSenderAccountList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BankSenderAccountList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_BankRecieveAccountList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BankRecieveAccountList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_TransactionBetweenBankAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_TransactionBetweenBankAccounts As Global.System.Web.UI.WebControls.SqlDataSource
End Class
