'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientManagement

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''Master_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Master_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''HeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddNewContactLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewContactLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ContactNameComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNameComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ContactNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ClientStaffName1GSMLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName1GSMLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientStaffName1GSMTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName1GSMTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ClientStaffName1GSMRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName1GSMRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ClientStaffName2GSMLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName2GSMLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientStaffName2GSMTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName2GSMTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ClientDocumentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientDocumentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientDocumentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientDocumentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''ClientStaffName1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientStaffName1TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName1TextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ClientStaffName1Required control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName1Required As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ClientStaffName2Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName2Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientStaffName2TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientStaffName2TextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ClientMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientMemoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientMemoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ClientRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalPopup As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''SqlDataSource_ContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ContactList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ClientList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ClientList As Global.System.Web.UI.WebControls.SqlDataSource
End Class
