'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FlatManagementWindow

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''HeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatCompanyNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatCompanyNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatCompanyNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatCompanyNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatProvinceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatProvinceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewProvince As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FlatProvinceComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatProvinceComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FlatProvinceRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatProvinceRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatVillageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatVillageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addnewVillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addnewVillage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FlatVillageComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatVillageComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FlatVillageRequired1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatVillageRequired1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatRoomNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatRoomNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatRoomNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatRoomNoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatBathRoomTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatBathRoomTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatBathRoomTypeComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatBathRoomTypeComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FlatAttachment1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatAttachment1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatAttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatAttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''FlatUploadedLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatUploadedLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FlatOfficalNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatOfficalNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatOfficalNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatOfficalNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatRentPriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatRentPriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatRentPriceRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatRentPriceRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''FlatrentPriceRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatrentPriceRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddnewCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddnewCity As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FlatCityComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatCityComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FlatCityRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatCityRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatPlaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatPlaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatPlaceRadTExtBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatPlaceRadTExtBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatBathroomNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatBathroomNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatBathroomNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatBathroomNoTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatMemoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatMemoRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''AddBasicData_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddBasicData_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''FlatEdit_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatEdit_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''SqlDataSource_ProvincesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ProvincesList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_CityList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_CityList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_VillageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_VillageList As Global.System.Web.UI.WebControls.SqlDataSource
End Class
