'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BuildingUpdateManagement

    '''<summary>
    '''headerPlaceHolderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headerPlaceHolderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''BuildingTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingTabStrip As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''BuildingMultiPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMultiPage As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''GeneralPageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralPageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''MFBuildingNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MFBuildingNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingOwnerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOwnerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingOwnerComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOwnerComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''BuildingOwnerRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOwnerRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingContactStaffNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingContactStaffNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingAddressLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BuildingAddressTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingAddressRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingFloorNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFloorNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingFloorNoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFloorNoRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingFlatNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFlatNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingFlatNoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFlatNoRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingOfficalNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficalNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingOfficalNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficalNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingCurrencyTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingCurrencyTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingCurrencyTypeComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingCurrencyTypeComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''BuildingCurrencyTypeRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingCurrencyTypeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingRentPriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingRentPriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingRentPriceRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingRentPriceRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingContactStaffGSMLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffGSMLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingContactStaffGSMContryCodeCombobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffGSMContryCodeCombobox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''BuildingContactStaffGSMTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffGSMTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingGPSLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingGPSLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingGPSTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingGPSTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingMapUrlLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMapUrlLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingMapURLCopyLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMapURLCopyLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BuildingMapUrlTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMapUrlTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingShopNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingShopNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingShopNoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingShopNoRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingOfficeNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficeNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingOfficeNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficeNoTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingMemoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMemoRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingAttachmentRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAttachmentRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''DownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SelectDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FlatPageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatPageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''FlatFloorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatFloorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatFloorComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatFloorComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FlatFloorRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatFloorRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatAttachmentRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatAttachmentRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''FlatDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatDescriptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatDescriptionEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatDescriptionEditor As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''FlatSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FlatListHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatListHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ShopPageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopPageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''ShopFloorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopFloorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopFloorComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopFloorComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ShopFloorRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopFloorRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ShopNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ShopNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ShopNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ShopNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ShopAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopAttachmentRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopAttachmentRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopDescriptionEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopDescriptionEditor As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''ShopSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''OfficePageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficePageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''OfficeFloorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeFloorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeFloorComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeFloorComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''OfficeFloorRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeFloorRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OfficeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OfficeNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OfficeNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OfficeNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OfficeAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeAttachmentRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeAttachmentRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeDescriptionEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeDescriptionEditor As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''OfficeSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''Building_modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Building_modal As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''newTabURLHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newTabURLHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SqlDataSource_CountryList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_CountryList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_OwnerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_OwnerList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Flats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Flats As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Shops control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Shops As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Offices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Offices As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_BuildingAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BuildingAttachments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_FlatAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_FlatAttachments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ShopAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ShopAttachments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_OfficeAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_OfficeAttachments As Global.System.Web.UI.WebControls.SqlDataSource
End Class
