'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FloorManagement

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FloorNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FloorNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FloorNamerequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorNamerequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FloorNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FloorNumberRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorNumberRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FloorNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FloorRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''FloorEdit_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorEdit_model As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''SqlDataSource_Floors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Floors As Global.System.Web.UI.WebControls.SqlDataSource
End Class
