'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BuildingAttachmentWindow

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''CloseButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''BuildingAttachmentTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAttachmentTabStrip As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''BuildingAttachmentMultiPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAttachmentMultiPage As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''ImagePageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagePageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''AttachmentImageHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentImageHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AttachmentNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AttachmentNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''AttachmentNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''AttachmentQualityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentQualityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AttachmentQualityRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentQualityRating As Global.Telerik.Web.UI.RadRating

    '''<summary>
    '''UploadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''AttachmentImageEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentImageEditor As Global.Telerik.Web.UI.RadImageEditor

    '''<summary>
    '''DocumentPageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocumentPageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DocAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DocAttachmentNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocAttachmentNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''DocNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''DocAttachmentUploadLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocAttachmentUploadLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DocAttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocAttachmentUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''DocAttachmentHyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocAttachmentHyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DocUploadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocUploadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''AttachmentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttachmentType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock
End Class
