'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BuildingManagement

    '''<summary>
    '''headerPlaceHolderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headerPlaceHolderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''PopMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMsg As Global.RealEstateManagementSystem.messageBox

    '''<summary>
    '''BuildingTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingTabStrip As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''ClearTabButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearTabButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ClearAllButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearAllButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''BuildingMultiPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMultiPage As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''GeneralPageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralPageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''MFBuildingNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MFBuildingNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingOwnerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOwnerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingOwnerComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOwnerComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''BuildingOwnerRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOwnerRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingContactStaffNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingContactStaffNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingAddressLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BuildingAddressTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingAddressRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAddressRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingFloorNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFloorNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingFloorNoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFloorNoRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingFlatNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFlatNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingFlatNoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingFlatNoRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingOfficalNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficalNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingOfficalNameRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficalNameRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingCurrencyTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingCurrencyTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingCurrencyTypeComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingCurrencyTypeComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''BuildingCurrencyTypeRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingCurrencyTypeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuildingRentPriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingRentPriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingRentPriceRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingRentPriceRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingContactStaffGSMLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffGSMLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingContactStaffGSMContryCodeCombobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffGSMContryCodeCombobox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''BuildingContactStaffGSMTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingContactStaffGSMTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingGPSLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingGPSLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingGPSTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingGPSTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingMapUrlLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMapUrlLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingMapURLCopyLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMapURLCopyLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BuildingMapUrlTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMapUrlTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingShopNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingShopNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingShopNoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingShopNoRadTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingOfficeNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficeNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingOfficeNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingOfficeNoTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BuildingMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingMemoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingMemoRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''BuildingAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuildingAttachmentTempRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuildingAttachmentTempRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''GeneralDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''GeneralSelectDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralSelectDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''GeneralSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FlatPageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatPageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''FlatHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatFloorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatFloorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatFloorComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatFloorComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FlatFloorRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatFloorRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FlatNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FlatAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatAttachmentTempRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatAttachmentTempRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''FlatDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FlatSelectDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatSelectDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FlatDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatDescriptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatDescriptionEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatDescriptionEditor As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''FlatSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FlatListHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatListHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlatTempRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatTempRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''FlatPreviousButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatPreviousButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FlatNextButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlatNextButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ShopPageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopPageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''ShopHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopFloorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopFloorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopFloorComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopFloorComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ShopFloorRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopFloorRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ShopNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ShopNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ShopNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ShopNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ShopAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopAttachmentTempRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopAttachmentTempRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ShopDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ShopSelectDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopSelectDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopDescriptionEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopDescriptionEditor As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''ShopSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShopTempRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopTempRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ShopPreviousButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopPreviousButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ShopNextButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShopNextButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''OfficePageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficePageView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''OfficeHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeHeaderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeFloorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeFloorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeFloorComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeFloorComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''OfficeFloorRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeFloorRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OfficeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OfficeNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OfficeNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNumberTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OfficeNumberRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNumberRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OfficeAttachmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeAttachmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeAttachmentTempRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeAttachmentTempRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''OfficeDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''OfficeSelectDownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeSelectDownloadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeDescriptionEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeDescriptionEditor As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''OfficeSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeSubmitButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OfficeTempRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeTempRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''OfficePreviousButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficePreviousButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''OfficeNextButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNextButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadWindowManager_modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager_modalPopup As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''Building_modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Building_modal As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''newTabURLHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newTabURLHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SqlDataSource_CountryList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_CountryList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_OwnerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_OwnerList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_FlatTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_FlatTemp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ShopTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ShopTemp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_OfficeTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_OfficeTemp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_BuildingAttachmentTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_BuildingAttachmentTemp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_FlatAttachmentTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_FlatAttachmentTemp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ShopAttachmentTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ShopAttachmentTemp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_OfficeAttachmentTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_OfficeAttachmentTemp As Global.System.Web.UI.WebControls.SqlDataSource
End Class
